I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 294, in script
    show image [nrg_string] at upper_left
Exception: DynamicImage ['images/energy_bar/4.png']: could not find image. ('images/energy_bar/4.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 294, in script
    show image [nrg_string] at upper_left
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/exports.py", line 765, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/display/scenelists.py", line 456, in add
    thing.set_transform_event("replace")
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/display/transform.py", line 743, in set_transform_event
    self.child.set_transform_event(event)
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/display/image.py", line 760, in set_transform_event
    self.find_target()
  File "/Users/kaia/Desktop/renpy-8.2.1-sdk/renpy/display/image.py", line 683, in find_target
    raise Exception(error)
Exception: DynamicImage ['images/energy_bar/4.png']: could not find image. ('images/energy_bar/4.png')

macOS-13.5-arm64-arm-64bit arm64
Ren'Py 8.2.1.24030407
kiwiskins 1.0
Wed Apr 24 11:18:07 2024
